From ubuntu:20.04

# see comments in Dockerfile-boxa

RUN apt-get update
RUN apt-get upgrade -y

RUN apt-get install -y net-tools vim bash iptables iputils-ping \
  traceroute iproute2 git build-essential

WORKDIR /
RUN git clone https://github.com/DhavalKapil/icmptunnel

WORKDIR /icmptunnel
RUN make all

CMD ["bash"]
